# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
NSBundle+Darwin.m
NSDateFormatter+Darwin.m
NSFileManager+Darwin.m
NSPathUtilities+Darwin.m
NSProcessInfo+Darwin.m
NSString+Darwin.m
NSTask+Darwin.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
MulleObjCLoader+MulleObjCDarwinFoundation.m
)
