#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleObjCOSFoundation-import-private.h
src/reflect/_MulleObjCOSFoundation-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleObjCOSFoundation-import.h
src/reflect/_MulleObjCOSFoundation-include.h
)

set( PUBLIC_HEADERS
src/MulleObjCLoader+MulleObjCOSFoundation.h
src/MulleObjCOSFoundation.h
src/import.h
src/include.h
)

