#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
.
reflect
)

set( PRIVATE_GENERATED_HEADERS
_MulleObjCOSWindowsFoundation-import-private.h
_MulleObjCOSWindowsFoundation-include-private.h
reflect/_MulleObjCWindowsFoundation-import-private.h
reflect/_MulleObjCWindowsFoundation-include-private.h
)

set( PRIVATE_HEADERS
import-private.h
)

set( PUBLIC_GENERATED_HEADERS
_MulleObjCOSWindowsFoundation-import.h
_MulleObjCOSWindowsFoundation-include.h
reflect/_MulleObjCWindowsFoundation-import.h
reflect/_MulleObjCWindowsFoundation-include.h
)

set( PUBLIC_HEADERS
MulleObjCLoader+MulleObjCOSWindowsFoundation.h
MulleObjCOSWindowsFoundation.h
NSCondition.h
import.h
)

