# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
.
reflect
Functions
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
reflect/_MulleObjCWindowsFoundation-import-private.h
reflect/_MulleObjCWindowsFoundation-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
import-private.h
include-private.h
)

#
# contents selected with patternfile ??-header--private-headers
#
set( PRIVATE_HEADERS
MulleObjCWindowsString+Private.h
NSDate+Windows-Private.h
NSTimeZone+Windows-Private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
reflect/_MulleObjCWindowsFoundation-export.h
reflect/_MulleObjCWindowsFoundation-import.h
reflect/_MulleObjCWindowsFoundation-include.h
reflect/_MulleObjCWindowsFoundation-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
import.h
include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
Functions/NSLog.h
Functions/mulle-windows-tm.h
MulleObjCDeps+MulleObjCOSWindowsFoundation.h
MulleObjCWindowsFoundation.h
NSErrorWindows.h
NSFileManager+Windows.h
NSString+Windows.h
NSTask+Windows.h
_NSWindowsDateFormatter.h
)

