# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 301fbe35-3942-43d1-bc03-7ac995535237;MulleObjCOSBaseFoundation;no-build,no-delete,no-dependency,no-fs,no-update;
# Disable with : `mulle-sourcetree mark MulleObjCOSBaseFoundation `
# Disable for this platform: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-cmake-sdk-<name>`
#
if( COLLECT_ALL_LOAD_OS_SPECIFIC_LIBRARIES_AS_NAMES)
   list( APPEND ALL_LOAD_OS_SPECIFIC_LIBRARIES "MulleObjCOSBaseFoundation")
else()
   if( NOT MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY)
      find_library( MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY NAMES
         MulleObjCOSBaseFoundation
      )
      message( STATUS "MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY is ${MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY)
         #
         # Add MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY to ALL_LOAD_OS_SPECIFIC_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-cmake-add`
         #
         list( APPEND ALL_LOAD_OS_SPECIFIC_LIBRARIES ${MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE_OBJC_OS_BASE_FOUNDATION_ROOT "${MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE_OBJC_OS_BASE_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-cmake-dependency`
         #
         foreach( _TMP_MULLE_OBJC_OS_BASE_FOUNDATION_NAME "MulleObjCOSBaseFoundation")
            set( _TMP_MULLE_OBJC_OS_BASE_FOUNDATION_DIR "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_DIR}")
               #
               include( "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_DIR}")
               #
               unset( MULLE_OBJC_OS_BASE_FOUNDATION_DEFINITIONS)
               unset( MULLE_OBJC_OS_BASE_FOUNDATION_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE_OBJC_OS_BASE_FOUNDATION_DEFINITIONS})
               include( "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE_OBJC_OS_BASE_FOUNDATION_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_DIR} not found")
            endif()
         endforeach()
         #
         # Search for "MulleObjCDeps+<name>.h" in include directory.
         # Disable with: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-cmake-loader`
         #
         if( NOT NO_INHERIT_OBJC_DEPS)
            foreach( _TMP_MULLE_OBJC_OS_BASE_FOUNDATION_NAME "MulleObjCOSBaseFoundation")
               set( _TMP_MULLE_OBJC_OS_BASE_FOUNDATION_FILE "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_NAME}/MulleObjCDeps+${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_NAME}.h")
               if( EXISTS "${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_FILE}")
                  list( APPEND INHERITED_OBJC_DEPS ${_TMP_MULLE_OBJC_OS_BASE_FOUNDATION_FILE})
                  break()
               endif()
            endforeach()
         endif()
      else()
         # Disable with: `mulle-sourcetree mark MulleObjCOSBaseFoundation no-require-link`
         message( SEND_ERROR "MULLE_OBJC_OS_BASE_FOUNDATION_LIBRARY was not found in MulleObjCOSBaseFoundation")
      endif()
   endif()
endif()
