# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
Functions/NSLog.m
Functions/mulle-windows-tm.c
NSBundle+Windows.m
NSCalendarDate+Windows.m
NSData+Windows.m
NSDate+Windows.m
NSDirectoryEnumerator+Windows.m
NSErrorWindows.m
NSFileHandle+Windows.m
NSFileManager+Windows.m
NSLocale+Windows.m
NSPathUtilities+Windows.m
NSPipe+Windows.m
NSProcessInfo+Windows.m
NSRunLoop+Windows.m
NSString+Windows.m
NSTask+Windows.m
NSTimeZone+Windows.m
_NSWindowsDateFormatter.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
MulleObjCDeps+MulleObjCOSWindowsFoundation.m
)
