/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 5A785563-00EB-4007-B8D6-5C97B529ED22 instead of MulleObjCPosixFoundation if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark MulleObjCPosixFoundation no-header`
//    rename:              `mulle-sde dependency|library set MulleObjCPosixFoundation include whatever.h`
//    reorder:             `mulle-sde dependency move MulleObjCPosixFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCPosixFoundation [no-]import`
//    toggle public:       `mulle-sde dependency mark MulleObjCPosixFoundation [no-]public`
//    toggle optional:     `mulle-sde dependency mark MulleObjCPosixFoundation [no-]require`
//    remove for platform: `mulle-sde dependency mark MulleObjCPosixFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // MulleObjCPosixFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCDarwinFoundation-include.h")
#  include "_MulleObjCDarwinFoundation-include.h"
# endif
#endif

