/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove MulleObjCOSBaseFoundation`
// (Use 6c6822fe-585d-4917-ab85-0261ee3ebe86 instead of MulleObjCOSBaseFoundation, if there are duplicate entries)
//
// You can tweak the following #import with these commands:
//    remove #import      : `mulle-sde dependency mark MulleObjCOSBaseFoundation no-header`
//    rename              : `mulle-sde dependency|library set MulleObjCOSBaseFoundation include whatever.h`
//    reorder             : `mulle-sde dependency move MulleObjCOSBaseFoundation <up|down>`
//    toggle #import      : `mulle-sde dependency mark MulleObjCOSBaseFoundation [no-]import`
//    toggle public       : `mulle-sde dependency mark MulleObjCOSBaseFoundation [no-]public`
//    toggle optional     : `mulle-sde dependency mark MulleObjCOSBaseFoundation [no-]require`
//    remove for platform : `mulle-sde dependency mark MulleObjCOSBaseFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCOSBaseFoundation/MulleObjCOSBaseFoundation.h>   // MulleObjCOSBaseFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCPosixFoundation-include.h")
#  include "_MulleObjCPosixFoundation-include.h"
# endif
#endif

