#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
.
reflect
)

set( PRIVATE_GENERATED_HEADERS
reflect/_MulleObjCBSDFoundation-import-private.h
reflect/_MulleObjCBSDFoundation-include-private.h
)

set( PRIVATE_HEADERS
import-private.h
include-private.h
)

set( PUBLIC_GENERATED_HEADERS
reflect/_MulleObjCBSDFoundation-import.h
reflect/_MulleObjCBSDFoundation-include.h
)

set( PUBLIC_HEADERS
import.h
include.h
mulle_bsd_tm.h
)

