# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: f38a8072-c7d3-4575-a1d7-d5decc9bceec;MulleObjCPosixFoundation;no-build,no-delete,no-dependency,no-fs,no-link,no-update;
# Disable with : `mulle-sourcetree mark MulleObjCPosixFoundation `
# Disable for this platform: `mulle-sourcetree mark MulleObjCPosixFoundation no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark MulleObjCPosixFoundation no-cmake-sdk-<name>`
#
if( NOT MULLE_OBJC_POSIX_FOUNDATION_HEADER)
   find_file( MULLE_OBJC_POSIX_FOUNDATION_HEADER NAMES
      MulleObjCPosixFoundation/MulleObjCPosixFoundation.h MulleObjCPosixFoundation/MulleObjCPosixFoundation.h
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
   )
   if( NOT MULLE_OBJC_POSIX_FOUNDATION_HEADER AND NOT DEPENDENCY_IGNORE_SYSTEM_HEADERS)
      find_file( MULLE_OBJC_POSIX_FOUNDATION_HEADER NAMES
         MulleObjCPosixFoundation/MulleObjCPosixFoundation.h MulleObjCPosixFoundation/MulleObjCPosixFoundation.h
      )
   endif()
   message( STATUS "MULLE_OBJC_POSIX_FOUNDATION_HEADER is ${MULLE_OBJC_POSIX_FOUNDATION_HEADER}")

   #
   # Add MULLE_OBJC_POSIX_FOUNDATION_HEADER to ALL_LOAD_HEADER_ONLY_LIBRARIES list.
   # Disable with: `mulle-sourcetree mark MulleObjCPosixFoundation no-cmake-add`
   #
   set( ALL_LOAD_HEADER_ONLY_LIBRARIES
      ${MULLE_OBJC_POSIX_FOUNDATION_HEADER}
      ${ALL_LOAD_HEADER_ONLY_LIBRARIES}
   )
   if( MULLE_OBJC_POSIX_FOUNDATION_HEADER)
      #
      # Inherit ObjC loader and link dependency info.
      # Disable with: `mulle-sourcetree mark MulleObjCPosixFoundation no-cmake-inherit`
      #
      get_filename_component( _TMP_MULLE_OBJC_POSIX_FOUNDATION_ROOT "${MULLE_OBJC_POSIX_FOUNDATION_HEADER}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_POSIX_FOUNDATION_NAME "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_ROOT}" NAME)
      get_filename_component( _TMP_MULLE_OBJC_POSIX_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_ROOT}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_POSIX_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_ROOT}" DIRECTORY)
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjCPosixFoundation no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_POSIX_FOUNDATION_NAME IN LISTS _TMP_MULLE_OBJC_POSIX_FOUNDATION_NAME)
         set( _TMP_MULLE_OBJC_POSIX_FOUNDATION_DIR "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_POSIX_FOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_DIR}")
            # we only want top level INHERIT_OBJC_DEPS, so disable them
            if( NOT NO_INHERIT_OBJC_DEPS)
               set( NO_INHERIT_OBJC_DEPS OFF)
            endif()
            list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
            set( NO_INHERIT_OBJC_DEPS ON)
            #
            include( "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
            list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_DIR}")
            #
            unset( MULLE_OBJC_POSIX_FOUNDATION_DEFINITIONS)
            unset( MULLE_OBJC_POSIX_FOUNDATION_RENDEZVOUS_GLOBALS)
            include( "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE_OBJC_POSIX_FOUNDATION_DEFINITIONS})
            include( "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND RENDEZVOUS_GLOBALS ${MULLE_OBJC_POSIX_FOUNDATION_RENDEZVOUS_GLOBALS})
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCDeps+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjCPosixFoundation no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_DEPS)
         foreach( _TMP_MULLE_OBJC_POSIX_FOUNDATION_NAME IN LISTS _TMP_MULLE_OBJC_POSIX_FOUNDATION_NAME)
            set( _TMP_MULLE_OBJC_POSIX_FOUNDATION_FILE "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_POSIX_FOUNDATION_NAME}/MulleObjCDeps+${_TMP_MULLE_OBJC_POSIX_FOUNDATION_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_POSIX_FOUNDATION_FILE}")
               list( APPEND INHERITED_OBJC_DEPS ${_TMP_MULLE_OBJC_POSIX_FOUNDATION_FILE})
               break()
            endif()
         endforeach()
      endif()
   else()
      # Disable with: `mulle-sourcetree mark MulleObjCPosixFoundation no-require`
      message( SEND_ERROR "MULLE_OBJC_POSIX_FOUNDATION_HEADER was not found in MulleObjCPosixFoundation/MulleObjCPosixFoundation.h MulleObjCPosixFoundation/MulleObjCPosixFoundation.h")
   endif()
endif()
