#
# This file will be included by cmake/share/sources.cmake
#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
_MulleGMTTimeZone+BSD.m
NSCalendarDate+BSD.m
NSDateFormatter+BSD.m
NSLocale+BSD.m
NSProcessInfo+BSD.m
NSTask+BSD.m
NSTimeZone+BSD.m
mulle_bsd_tm.c
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
MulleObjCLoader+MulleObjCBSDFoundation.m
)
