/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use c9b589de-edca-4be3-81a7-401e29bb43aa instead of MulleObjCPosixFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCPosixFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCPosixFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCPosixFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCPosixFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCPosixFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCPosixFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCPosixFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // MulleObjCPosixFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCLinuxFoundation-include.h")
#  include "_MulleObjCLinuxFoundation-include.h"
# endif
#endif

