# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
.
reflect
Timezone
Functions
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
reflect/_MulleObjCPosixFoundation-import-private.h
reflect/_MulleObjCPosixFoundation-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
import-private.h
include-private.h
)

#
# contents selected with patternfile ??-header--private-headers
#
set( PRIVATE_HEADERS
NSDate+Posix-Private.h
NSLocale+Posix-Private.h
NSTimeZone+Posix-Private.h
Timezone/private.h
)

#
# contents selected with patternfile ??-header--project-only-headers
#
set( PROJECT_ONLY_HEADERS
dependencies.inc
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
reflect/_MulleObjCPosixFoundation-export.h
reflect/_MulleObjCPosixFoundation-import.h
reflect/_MulleObjCPosixFoundation-include.h
reflect/_MulleObjCPosixFoundation-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
import.h
include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
Functions/mulle-posix-tm.h
MulleObjCPosixFoundation.h
NSError+Posix.h
NSLocale+Posix.h
_NSPosixDateFormatter.h
Timezone/tzfile.h
)

