# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
Functions/NSLog.m
Functions/mulle-posix-tm.c
MulleObjCPOSIXString.m
NSBundle+Posix.m
NSCalendarDate+Posix.m
NSData+Posix.m
NSDate+Posix.m
NSDirectoryEnumerator+Posix.m
NSError+Posix.m
NSFileHandle+Posix.m
NSFileManager+Posix.m
NSLocale+Posix.m
NSPageAllocation+Posix.m
NSPipe+Posix.m
_NSPosixDateFormatter.m
NSProcessInfo+Posix.m
NSRunLoop+Posix.m
NSTask+Posix.m
NSTimeZone+Posix.m
Timezone/localtime.c
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
MulleObjCLoader+MulleObjCPosixFoundation.m
)
