#
# This file will be included by cmake/share/sources.cmake
#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
Functions/NSLog.m
Functions/mulle_posix_tm.c
MulleObjCPOSIXString.m
NSBundle+Posix.m
NSCalendarDate+Posix.m
NSData+Posix.m
NSDate+Posix.m
NSDirectoryEnumerator+Posix.m
NSError+Posix.m
NSFileHandle+Posix.m
NSFileManager+Posix.m
NSLocale+Posix.m
NSPageAllocation+Posix.m
NSPipe+Posix.m
_NSPosixDateFormatter.m
NSProcessInfo+Posix.m
NSRunLoop+Posix.m
NSTask+Posix.m
NSTimeZone+Posix.m
Timezone/localtime.c
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
MulleObjCLoader+MulleObjCPosixFoundation.m
)
