/* DO:    #import this files in public headers

   DONT:  #import this file in private headers
          #import this files in directly in sources
          #include this file anywhere
*/

/* This is a central include file to keep dependencies out of the library
   Objective-C files. It is usally imported by Objective-C .h files only.
   .m and .aam use import-private.h.
*/


#ifdef MULLE_OBJC_WINDOWS_FOUNDATION_BUILD
# define MULLE_OBJC_WINDOWS_FOUNDATION_GLOBAL        MULLE_C_GLOBAL
# define MULLE_OBJC_WINDOWS_FOUNDATION_GLOBAL_VAR    MULLE_C_GLOBAL_VAR
#else
# if defined( MULLE_OBJC_WINDOWS_FOUNDATION_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( MULLE_OBJC_WINDOWS_FOUNDATION_INCLUDE_STATIC))
#  define MULLE_OBJC_WINDOWS_FOUNDATION_GLOBAL       MULLE_C_EXTERN_GLOBAL
# else
#  define MULLE_OBJC_WINDOWS_FOUNDATION_GLOBAL       extern
# endif
# define MULLE_OBJC_WINDOWS_FOUNDATION_GLOBAL_VAR
#endif

/* Include the header file automatically generated by mulle-sourcetree-to-c.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#import "_MulleObjCWindowsFoundation-import.h"




/* You can add some more import statements here */
