/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleObjCOSBaseFoundation_include_private_h__
#define _MulleObjCOSBaseFoundation_include_private_h__

// How to tweak the following mulle-mmap #include
//    remove:             `mulle-sourcetree mark mulle-mmap no-header`
//    rename:             `mulle-sde dependency|library set mulle-mmap include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mulle-mmap [no-]import`
//    toggle localheader: `mulle-sourcetree mark mulle-mmap [no-]localheader`
//    toggle public:      `mulle-sourcetree mark mulle-mmap [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-mmap [no-]require`
//    remove for os:      `mulle-sourcetree mark mulle-mmap no-os-<osname>`
# if defined( __has_include) && __has_include("mulle-mmap.h")
#   include "mulle-mmap.h"   // mulle-mmap
# else
#   include <mulle-mmap/mulle-mmap.h>   // mulle-mmap
# endif

#endif
