/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_os_base_foundation_include_private_h__
#define _mulle_objc_os_base_foundation_include_private_h__

// You can tweak the following #include with these commands.
// (Use CEC76AC7-2529-4DCC-A637-A393AD496D6D instead of mulle-mmap if there are duplicate entries)
//    remove:             `mulle-sde dependency mark mulle-mmap no-header`
//    rename:             `mulle-sde dependency|library set mulle-mmap include whatever.h`
//    reorder:            `mulle-sde dependency move mulle-mmap <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-mmap [no-]import`
//    toggle public:      `mulle-sde dependency mark mulle-mmap [no-]public`
//    toggle optional:    `mulle-sde dependency mark mulle-mmap [no-]require`
//    remove for platform:`mulle-sde dependency mark mulle-mmap no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-mmap/mulle-mmap.h>   // mulle-mmap

#endif
