/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _MulleObjCOSFoundation_import_h__
#define _MulleObjCOSFoundation_import_h__

// How to tweak the following src/OSBase #import
//    remove:          `mulle-sourcetree mark src/OSBase no-header`
//    rename:          `mulle-sourcetree mark src/OSBase set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark src/OSBase [no-]import`
//    toggle public:   `mulle-sourcetree mark src/OSBase [no-]public`
//    toggle optional: `mulle-sourcetree mark src/OSBase [no-]require`
//    remove for os:   `mulle-sourcetree mark src/OSBase no-os-<osname>`
# import <MulleObjCOSBaseFoundation/MulleObjCOSBaseFoundation.h>   // src/OSBase

// How to tweak the following src/Posix #import
//    remove:          `mulle-sourcetree mark src/Posix no-header`
//    rename:          `mulle-sourcetree mark src/Posix set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark src/Posix [no-]import`
//    toggle public:   `mulle-sourcetree mark src/Posix [no-]public`
//    toggle optional: `mulle-sourcetree mark src/Posix [no-]require`
//    remove for os:   `mulle-sourcetree mark src/Posix no-os-<osname>`
# import <MulleObjCPosixFoundation/MulleObjCPosixFoundation.h>   // src/Posix

// How to tweak the following src/Windows #import
//    remove:          `mulle-sourcetree mark src/Windows no-header`
//    rename:          `mulle-sourcetree mark src/Windows set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark src/Windows [no-]import`
//    toggle public:   `mulle-sourcetree mark src/Windows [no-]public`
//    toggle optional: `mulle-sourcetree mark src/Windows [no-]require`
//    remove for os:   `mulle-sourcetree mark src/Windows no-os-<osname>`
# if defined( _WIN32) || defined( __windows__)
#  import <Windows/Windows.h>   // src/Windows
# endif

#include "_MulleObjCOSFoundation-include.h"


#endif
