/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_OBJC_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#ifndef _mulle_objc_windows_foundation__export_h__
#define _mulle_objc_windows_foundation__export_h__


#import "NSLog.h"
#import "MulleObjCDeps+MulleObjCOSWindowsFoundation.h"
#import "NSErrorWindows.h"
#import "NSFileManager+Windows.h"
#import "NSString+Windows.h"
#import "NSTask+Windows.h"


#endif
