/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 301fbe35-3942-43d1-bc03-7ac995535237 instead of MulleObjCOSBaseFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCOSBaseFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCOSBaseFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCOSBaseFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCOSBaseFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCOSBaseFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCOSBaseFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCOSBaseFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCOSBaseFoundation/MulleObjCOSBaseFoundation.h>   // MulleObjCOSBaseFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCWindowsFoundation-include.h")
#  include "_MulleObjCWindowsFoundation-include.h"
# endif
#endif

