#
# This file will be included by cmake/share/Headers.cmake
#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
.
Categories
Functions
reflect
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
reflect/_MulleObjCOSBaseFoundation-import-private.h
reflect/_MulleObjCOSBaseFoundation-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
import-private.h
include-private.h
)

#
# contents selected with patternfile ??-header--private-headers
#
set( PRIVATE_HEADERS
Categories/NSArray+OSBase-Private.h
Categories/NSDate+OSBase-Private.h
Categories/NSDictionary+OSBase-Private.h
Functions/NSPageAllocation-Private.h
NSBundle-Private.h
NSFileManager-Private.h
NSPathUtilities+OSBase-Private.h
NSRunLoop-Private.h
NSTask-Private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
reflect/_MulleObjCOSBaseFoundation-export.h
reflect/_MulleObjCOSBaseFoundation-import.h
reflect/_MulleObjCOSBaseFoundation-include.h
reflect/_MulleObjCOSBaseFoundation-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
import.h
include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
Categories/NSArray+OSBase.h
Categories/NSCalendarDate+NSUserDefaults.h
Categories/NSConditionLock+NSDate.h
Categories/NSCondition+NSDate.h
Categories/NSData+OSBase.h
Categories/NSDictionary+OSBase.h
Categories/NSLock+NSDate.h
Categories/NSString+CString.h
Categories/NSString+OSBase.h
Categories/NSTask+System.h
Functions/NSLog.h
Functions/NSPageAllocation.h
Functions/NSPathUtilities.h
MulleObjCOSBaseFoundation.h
NSBundle.h
NSData+MulleMemoryMapping.h
NSDirectoryEnumerator.h
NSFileHandle+NSRunLoop.h
NSFileHandle.h
NSFileManager.h
NSObject+NSRunLoop.h
NSPipe.h
NSProcessInfo.h
NSRunLoop.h
NSTask.h
NSTimer+NSRunLoop.h
NSTimer.h
NSUserDefaults.h
)

