#
# This file will be included by cmake/share/sources.cmake
#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
Categories/NSArray+OSBase-Private.m
Categories/NSArray+OSBase.m
Categories/NSCalendarDate+NSUserDefaults.m
Categories/NSConditionLock+NSDate.m
Categories/NSCondition+NSDate.m
Categories/NSData+OSBase.m
Categories/NSDictionary+OSBase-Private.m
Categories/NSDictionary+OSBase.m
Categories/NSLock+NSDate.m
Categories/NSString+CString.m
Categories/NSString+OSBase.m
Categories/NSTask+System.m
Functions/NSPageAllocation.m
Functions/NSPathUtilities.m
NSBundle.m
NSData+MulleMemoryMapping.m
NSDirectoryEnumerator.m
NSFileHandle+NSRunLoop.m
NSFileHandle.m
NSFileManager.m
NSObject+NSRunLoop.m
NSPipe.m
NSProcessInfo.m
NSRunLoop.m
NSTask.m
NSTimer+NSRunLoop.m
NSTimer.m
NSUserDefaults.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
MulleObjCLoader+MulleObjCOSBaseFoundation.m
)
